apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"5"},"creationTimestamp":"2025-10-12T18:54:13Z","generation":9,"labels":{"app":"synergychat-web"},"name":"synergychat-web","namespace":"default","resourceVersion":"178716","uid":"aa8e66af-a8cc-424a-9e65-caf5e3e8ae95"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-web"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-10-14T05:32:20+03:00"},"labels":{"app":"synergychat-web"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-web-configmap"}}],"image":"docker.io/bootdotdev/synergychat-web:latest","imagePullPolicy":"Always","name":"synergychat-web","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2025-10-12T18:54:13Z","lastUpdateTime":"2025-10-14T02:32:29Z","message":"ReplicaSet \"synergychat-web-547946564f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2025-10-14T20:34:29Z","lastUpdateTime":"2025-10-14T20:34:29Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":9,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2025-10-12T18:54:13Z"
  generation: 10
  labels:
    app: synergychat-web
  name: synergychat-web
  namespace: default
  resourceVersion: "182316"
  uid: aa8e66af-a8cc-424a-9e65-caf5e3e8ae95
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-14T05:32:20+03:00"
      labels:
        app: synergychat-web
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: synergychat-web-configmap
          image: docker.io/bootdotdev/synergychat-web:latest
          imagePullPolicy: Always
          name: synergychat-web
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2025-10-12T18:54:13Z"
      lastUpdateTime: "2025-10-14T02:32:29Z"
      message: ReplicaSet "synergychat-web-547946564f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-10-14T20:34:29Z"
      lastUpdateTime: "2025-10-14T20:34:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 10
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
